epoll:
  image: epoll
  hostname: epoll
  expose:
    - "8001"
  ports:
    - "8001:8001"
  working_dir:  /workspace/base/epoll
  volumes:
    - ./../:/workspace/base/epoll
  extra_hosts:
    - "epoll.dev:127.0.0.1"
  environment:
    - TERM=xterm
